[package]
name = "muse"
version = "0.0.1"
edition = "2021"

[dependencies]
eframe = { version = "0.28.1", features = ["default"] }
# egui = "0.28.1
egui_extras = { version = "0.28.1", features = ["default", "all_loaders"] }
env_logger = "0.11.5"
image = { version = "0.25.2", features = ["default-formats"] }
itertools = "0.13.0"
resvg = "0.44.0"
